// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user-service.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user/user-service.proto
	user/user.proto

It has these top-level messages:
	CreateUserRequest
	CreateUserReply
	GetUsersRequest
	GetUsersReply
	GetUserByEmailRequest
	User
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// create user
type CreateUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserReply struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserReply) Reset()                    { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string            { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()               {}
func (*CreateUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// get user
type GetUsersRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUsersRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetUsersReply struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetUsersReply) Reset()                    { *m = GetUsersReply{} }
func (m *GetUsersReply) String() string            { return proto.CompactTextString(m) }
func (*GetUsersReply) ProtoMessage()               {}
func (*GetUsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// get user by email
type GetUserByEmailRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *GetUserByEmailRequest) Reset()                    { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()               {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "user.CreateUserReply")
	proto.RegisterType((*GetUsersRequest)(nil), "user.GetUsersRequest")
	proto.RegisterType((*GetUsersReply)(nil), "user.GetUsersReply")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "user.GetUserByEmailRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersReply, error)
	GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUsersReply, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := grpc.Invoke(ctx, "/user.UserService/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersReply, error) {
	out := new(GetUsersReply)
	err := grpc.Invoke(ctx, "/user.UserService/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailRequest, opts ...grpc.CallOption) (*GetUsersReply, error) {
	out := new(GetUsersReply)
	err := grpc.Invoke(ctx, "/user.UserService/GetUserByEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersReply, error)
	GetUserByEmail(context.Context, *GetUserByEmailRequest) (*GetUsersReply, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetUserByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserService_GetUserByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user-service.proto",
}

func init() { proto.RegisterFile("user/user-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x07, 0x11, 0xba, 0xc5, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x7a, 0x05, 0x45, 0xf9, 0x25,
	0xf9, 0x42, 0x2c, 0x20, 0x31, 0x29, 0x7e, 0xb8, 0x34, 0x44, 0x58, 0xc9, 0x98, 0x4b, 0xd0, 0xb9,
	0x28, 0x35, 0xb1, 0x24, 0x35, 0xb4, 0x38, 0xb5, 0x28, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44,
	0x48, 0x8e, 0x0b, 0xac, 0x5a, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x4b, 0x0f, 0xac, 0x1e,
	0xac, 0x00, 0x2c, 0xae, 0x64, 0xc8, 0xc5, 0x8f, 0xac, 0xa9, 0x20, 0xa7, 0x92, 0xa0, 0x16, 0x65,
	0x2e, 0x7e, 0xf7, 0xd4, 0x12, 0x90, 0x40, 0x31, 0xcc, 0x16, 0x01, 0x2e, 0xe6, 0xcc, 0x94, 0x62,
	0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x10, 0x53, 0xc9, 0x90, 0x8b, 0x17, 0xa1, 0x08, 0x64,
	0xaa, 0x02, 0x17, 0x2b, 0x48, 0x37, 0x44, 0x11, 0xaa, 0xb1, 0x10, 0x09, 0x25, 0x5d, 0x2e, 0x51,
	0xa8, 0x16, 0xa7, 0x4a, 0xd7, 0xdc, 0xc4, 0xcc, 0x1c, 0x98, 0xe9, 0x22, 0x5c, 0xac, 0xa9, 0x20,
	0x3e, 0xd8, 0x45, 0x9c, 0x41, 0x10, 0x8e, 0xd1, 0x59, 0x46, 0x2e, 0x6e, 0x90, 0xe2, 0x60, 0x48,
	0xd8, 0x08, 0xd9, 0x71, 0x71, 0x21, 0x7c, 0x22, 0x24, 0x0e, 0x31, 0x1f, 0x23, 0x40, 0xa4, 0x44,
	0x31, 0x25, 0x0a, 0x72, 0x2a, 0x95, 0x18, 0x84, 0x2c, 0xb8, 0x38, 0x60, 0x2e, 0x16, 0x82, 0x2a,
	0x42, 0xf3, 0xa6, 0x94, 0x30, 0xba, 0x30, 0x44, 0xa7, 0x0b, 0x17, 0x1f, 0xaa, 0xc3, 0x85, 0xa4,
	0x51, 0x14, 0xa2, 0x7a, 0x07, 0x87, 0x29, 0x4e, 0x6c, 0x51, 0xe0, 0xe0, 0x4d, 0x62, 0x03, 0xc7,
	0xa6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x65, 0x43, 0x32, 0xff, 0x01, 0x00, 0x00,
}
